"""Bridging async and sync code: `run_sync`, `iter_sync`, `ctx_sync`, `maybe_await`, and `then`, plus `Debounce` for coalescing bursts of calls

Docs: https://fastcore.fast.ai/aio.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03c_aio.ipynb.

# %% auto #0
__all__ = ['run_sync', 'iter_sync', 'ctx_sync', 'maybe_await', 'then', 'acache', 'CachedAwaitable', 'reawaitable',
           'is_async_callable', 'to_aiter', 'maybe_aiter', 'mapa', 'noopa', 'Debounce', 'debounced', 'throttled']

# %% ../nbs/03c_aio.ipynb #7e2193be
import asyncio,threading
from contextlib import contextmanager
from functools import wraps
from .imports import *
from .xtras import UNSET
from .basics import *

# %% ../nbs/03c_aio.ipynb #ac2bc26d
_loop,_loop_lock = None,threading.Lock()

def _get_loop():
    global _loop
    with _loop_lock:
        if _loop is None:
            _loop = asyncio.new_event_loop()
            threading.Thread(target=_loop.run_forever, daemon=True, name='run_sync').start()
    return _loop

def run_sync(coro):
    "Run coroutine `coro` to completion from sync code and return its result"
    loop = _get_loop()
    try: reentrant = asyncio.get_running_loop() is loop
    except RuntimeError: reentrant = False
    if reentrant:
        coro.close()
        raise RuntimeError('run_sync called from its own event loop; use `await` instead')
    fut = asyncio.run_coroutine_threadsafe(coro, loop)
    try: return fut.result()
    except KeyboardInterrupt:
        fut.cancel()
        raise

# %% ../nbs/03c_aio.ipynb #6bef7885
def iter_sync(agen):
    "Iterate async generator `agen` from sync code"
    try:
        while True: yield run_sync(agen.__anext__())
    except StopAsyncIteration: pass
    finally: run_sync(agen.aclose())

# %% ../nbs/03c_aio.ipynb #e2a3ba49
@contextmanager
def ctx_sync(acm):
    "Use async context manager `acm` in a plain `with` block"
    res = run_sync(acm.__aenter__())
    try: yield res
    except BaseException as e:
        if not run_sync(acm.__aexit__(type(e), e, e.__traceback__)): raise
    else: run_sync(acm.__aexit__(None,None,None))

# %% ../nbs/03c_aio.ipynb #2a2643a1
async def maybe_await(o):
    "Await `o` if needed, and return it"
    from inspect import isawaitable
    return await o if isawaitable(o) else o

# %% ../nbs/03c_aio.ipynb #243df6dc
def then(x, *fs):
    "Pipe `x` through each of `fs`, awaiting values as needed; result is awaitable only if `x` or a step result is"
    from inspect import isawaitable
    async def _go(x, fs):
        x = await x
        for f in fs: x = await maybe_await(f(x))
        return x
    for i,f in enumerate(fs):
        if isawaitable(x): return _go(x, fs[i:])
        x = f(x)
    return _go(x, ()) if isawaitable(x) else x

# %% ../nbs/03c_aio.ipynb #97920a9d
def acache(f):
    "Cache results of async function `f`"
    cache = {}
    @wraps(f)
    async def _inner(*args, **kwargs):
        key = (args, tuple(sorted(kwargs.items())))
        if key not in cache: cache[key] = await f(*args, **kwargs)
        return cache[key]
    _inner.cache_clear = cache.clear
    return _inner

# %% ../nbs/03c_aio.ipynb #19cb9a0d
class CachedAwaitable:
    "Cache the result from an awaitable"
    def __init__(self, o): self.o,self.value = o,UNSET
    def __await__(self):
        if self.value is UNSET: self.value = yield from self.o.__await__()
        return self.value

# %% ../nbs/03c_aio.ipynb #f91e2e87
def reawaitable(func:callable):
    "Wraps the result of an asynchronous function into an object which can be awaited more than once"
    @wraps(func)
    def _f(*args, **kwargs): return CachedAwaitable(func(*args, **kwargs))
    return _f

# %% ../nbs/03c_aio.ipynb #9a195ca5
def is_async_callable(obj):
    "Check if `obj` is an async callable, handling `partial` wrappers and callable instances"
    # Implementation from Starlette; Copyright © 2018, Encode OSS Ltd.
    from asyncio import iscoroutinefunction
    while isinstance(obj, partial): obj = obj.func
    return iscoroutinefunction(obj) or (callable(obj) and iscoroutinefunction(obj.__call__))

# %% ../nbs/03c_aio.ipynb #38b2fbf0
async def to_aiter(items):
    "Async yield each item in `items` with `asyncio.sleep(0)` between"
    import asyncio
    for item in items:
        await asyncio.sleep(0)
        yield item

# %% ../nbs/03c_aio.ipynb #2eb5949b
def maybe_aiter(items):
    "If `items` already async, return it; otherwise to_aiter"
    return items if hasattr(items, '__aiter__') else to_aiter(items)

# %% ../nbs/03c_aio.ipynb #f522e97a
async def mapa(f, items):
    "Async `map`; apply `f` (sync or async) to `items` (sync or async iter) concurrently via `gather`"
    from asyncio import gather
    return await gather(*[maybe_await(f(o)) async for o in maybe_aiter(items)])

# %% ../nbs/03c_aio.ipynb #ecd40d0e
async def noopa(x=None, *args, **kwargs):
    "Do nothing (async)"
    return x

# %% ../nbs/03c_aio.ipynb #314d1e40
class Debounce:
    "Coalesce calls to `f` into one, made `wait` secs after calls stop (or `max_wait` secs after they start)"
    def __init__(self, f, wait, max_wait=None, leading=False, trailing=True):
        assert leading or trailing,"one of `leading`/`trailing` must be set"
        store_attr()
        self._task,self._q = None,None
        try: self._loop = asyncio.get_running_loop()
        except RuntimeError: self._loop = None

    def _put_latest(self, q, call):
        if q.full(): q.get_nowait()
        q.put_nowait(call)

    def __call__(self, *args, **kw):
        try: loop = asyncio.get_running_loop()
        except RuntimeError:
            if self._loop is None: raise RuntimeError('Debounce must first be called from an async event loop') from None
            return self._loop.call_soon_threadsafe(partial(self.__call__, *args, **kw))

        if self._loop is None: self._loop = loop
        elif loop is not self._loop: return self._loop.call_soon_threadsafe(partial(self.__call__, *args, **kw))

        self._deadline = self._loop.time()+self.wait
        call = (args, kw)
        if self._task and not self._task.done(): self._put_latest(self._q, call)
        else:
            self._q = asyncio.Queue(maxsize=1)
            self._cap = self._loop.time()+self.max_wait if self.max_wait else float('inf')
            if not self.leading: self._put_latest(self._q, call)
            self._task = self._loop.create_task(self._run(self._q, call if self.leading else None))

    async def _fire(self, p): await maybe_await(self.f(*p[0], **p[1]))
    async def _run(self, q, first):
        if first is not None: await self._fire(first)

        while True:
            delay = min(self._deadline,self._cap) - self._loop.time()
            if delay>0: await asyncio.sleep(delay); continue
            if not self.trailing:
                if not q.empty(): q.get_nowait()  # drop the rest of the burst
                return
            if q.empty(): return
            await self._fire(q.get_nowait())
            if q.empty(): return
            if self.max_wait: self._cap = self._loop.time()+self.max_wait

    def cancel(self):
        "Discard any pending call"
        if self._task and not self._task.done(): self._task.cancel()
        self._task,self._q = None,None

    async def flush(self):
        "Run any pending call now instead of waiting"
        p = self._q.get_nowait() if self._q and not self._q.empty() else None
        self.cancel()
        if p is not None: await self._fire(p)

    def __set_name__(self, owner, name): self._name = name
    def __get__(self, obj, objtype=None):
        if obj is None: return self
        res = obj.__dict__[self._name] = Debounce(partial(self.f, obj), self.wait, self.max_wait, self.leading, self.trailing)
        return res

# %% ../nbs/03c_aio.ipynb #7d9f6bcf
def debounced(wait, max_wait=None, leading=False, trailing=True):
    "Decorator: `Debounce` a function or method"
    return partial(Debounce, wait=wait, max_wait=max_wait, leading=leading, trailing=trailing)

def throttled(wait, leading=False):
    "Decorator: fire at most once per `wait` secs (`Debounce` with `max_wait=wait`)"
    return debounced(wait, max_wait=wait, leading=leading)
