"""Concise HTML generation and namespace-aware XML construction.

`ft(tag, *children, **attrs)` builds an `FT` tree — a lightweight XML/HTML element — and `to_xml` renders it (this is the foundation [fasthtml](https://fastht.ml) builds on). The common HTML tags are predefined as `ft` partials (`Div`, `P`, `A`, ...). Attributes are passed as keywords: use `klass` and `fr` for the reserved words `class` and `for`, `_` in an attr name becomes `-`, and attrs can be got and set on the object directly. Children can also be supplied after the attrs by calling the element, e.g. `Div(id='x')(child1, child2)`:

```python
t = Div(P('hi', klass='a'), hx_get='/get')
test_eq(to_xml(t), '<div hx-get="/get">\n  <p class="a">hi</p>\n</div>\n')
test_eq(to_xml(Div(id='x')('child')), '<div id="x">child</div>\n')
```

`E(prefix='', attr_ns=None, ns=None)` creates a namespace-bound XML factory. `e = E('w', attr_ns='w', ns={'w': uri})` supports expressions such as `e.tcW(type='dxa', w=2400)`. Tags and attributes preserve case. `prefix__name` selects an attribute namespace; `attrs_` accepts literal names. Expressions compose with text and ordered collections, retain their namespace bindings, and serialize as UTF-8 with `.bytes()`. XML text is escaped and booleans become `true`/`false`. The existing `ft` and `to_xml` APIs keep their HTML behavior.

Docs: https://fastcore.fast.ai/xml.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_xml.ipynb.

# %% auto #0
__all__ = ['voids', 'attrmap', 'valmap', 'FT', 'ft', 'Html', 'Safe', 'to_xml', 'dict2xml', 'highlight', 'showtags', 'mk_getattr',
           'XML', 'E', 'Head', 'Title', 'Meta', 'Link', 'Style', 'Body', 'Pre', 'Code', 'Div', 'Span', 'P', 'H1', 'H2',
           'H3', 'H4', 'H5', 'H6', 'Strong', 'Em', 'B', 'I', 'U', 'S', 'Strike', 'Sub', 'Sup', 'Hr', 'Br', 'Img', 'A',
           'Nav', 'Ul', 'Ol', 'Li', 'Dl', 'Dt', 'Dd', 'Table', 'Thead', 'Tbody', 'Tfoot', 'Tr', 'Th', 'Td', 'Caption',
           'Col', 'Colgroup', 'Form', 'Input', 'Textarea', 'Button', 'Select', 'Option', 'Label', 'Fieldset', 'Legend',
           'Details', 'Summary', 'Main', 'Header', 'Footer', 'Section', 'Article', 'Aside', 'Figure', 'Figcaption',
           'Mark', 'Small', 'Iframe', 'Object', 'Embed', 'Param', 'Video', 'Audio', 'Source', 'Canvas', 'Svg', 'Math',
           'Script', 'Noscript', 'Template', 'Slot']

# %% ../nbs/09_xml.ipynb #f6c9a7f5
from .utils import *

import types,json,re

from dataclasses import dataclass, asdict
from typing import Mapping
from functools import partial
from html import escape

# %% ../nbs/09_xml.ipynb #e1b62c2c
def _fix_k(k): return k if k=='_' else k.lstrip('_').replace('_', '-')

# %% ../nbs/09_xml.ipynb #159d3560
_specials = set('@.-!~:[](){}$%^&*+=|/?<>,`')

def attrmap(o):
    if _specials & set(o): return o
    o = dict(htmlClass='class', cls='class', _class='class', klass='class',
             _for='for', fr='for', htmlFor='for').get(o, o)
    return _fix_k(o)

# %% ../nbs/09_xml.ipynb #6f000a63
def valmap(o):
    if is_listy(o): return ' '.join(map(str,o)) if o else None
    if isinstance(o, dict): return '; '.join(f"{k}:{v}" for k,v in o.items()) if o else None
    return o

# %% ../nbs/09_xml.ipynb #ddc7d705
def _flatten_tuple(tup):
    if not any(isinstance(item, tuple) for item in tup): return tup
    result = []
    for item in tup:
        if isinstance(item, tuple): result.extend(item)
        else: result.append(item)
    return tuple(result)

# %% ../nbs/09_xml.ipynb #df5d12c7
def _preproc(c, kw, attrmap=attrmap, valmap=valmap):
    if len(c)==1 and isinstance(c[0], (types.GeneratorType, map, filter)): c = tuple(c[0])
    attrs = {attrmap(k.lower()):valmap(v) for k,v in kw.items() if v is not None}
    return _flatten_tuple(c),attrs

# %% ../nbs/09_xml.ipynb #b06c10f6
class FT:
    "A 'Fast Tag' structure, containing `tag`,`children`,and `attrs`"
    def __init__(self, tag:str, cs:tuple, attrs:dict=None, void_=False, **kwargs):
        assert isinstance(cs, tuple)
        self.tag,self.children,self.attrs,self.void_ = tag,cs,attrs,void_
        self.listeners_ = []
    
    def on(self, f): self.listeners_.append(f)
    def changed(self):
        [f(self) for f in self.listeners_]
        return self

    def __setattr__(self, k, v):
        if len(k)>1 and k.startswith('__') or k[-1]=='_' or k in ('tag','children','attrs','void_'): return super().__setattr__(k,v)
        self.attrs[_fix_k(k)] = v
        self.changed()

    def __getattr__(self, k):
        if k.startswith('__'): raise AttributeError(k)
        return self.get(k)

    @property
    def list(self): return [self.tag,self.children,self.attrs]
    def get(self, k, default=None): return self.attrs.get(_fix_k(k), default)
    
    def __repr__(self): return f'{self.tag}({self.children},{self.attrs})'
    def __iter__(self): return iter(self.children)
    def __getitem__(self, idx): return self.children[idx]
    
    def __setitem__(self, i, o):
        self.children = self.children[:i] + (o,) + self.children[i+1:]
        self.changed()

    def __call__(self, *c, **kw):
        c,kw = _preproc(c,kw)
        if c: self.children = self.children+c
        if kw: self.attrs = {**self.attrs, **kw}
        return self.changed()

    def set(self, *c, **kw):
        "Set children and/or attributes (chainable)"
        c,kw = _preproc(c,kw)
        if c: self.children = c
        if kw:
            self.attrs = {k:v for k,v in self.attrs.items() if k in ('id','name')}
            self.attrs = {**self.attrs, **kw}
        return self.changed()

# %% ../nbs/09_xml.ipynb #06718948
def ft(tag:str, *c, void_:bool=False, attrmap:callable=attrmap, valmap:callable=valmap, ft_cls=FT, **kw):
    "Create an `FT` structure for `to_xml()`"
    return ft_cls(tag.lower(),*_preproc(c,kw,attrmap=attrmap, valmap=valmap), void_=void_)

# %% ../nbs/09_xml.ipynb #45489975
voids = set('area base br col command embed hr img input keygen link meta param source track wbr !doctype'.split())
_g = globals()
_all_ = ['Head', 'Title', 'Meta', 'Link', 'Style', 'Body', 'Pre', 'Code',
    'Div', 'Span', 'P', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Strong', 'Em', 'B',
    'I', 'U', 'S', 'Strike', 'Sub', 'Sup', 'Hr', 'Br', 'Img', 'A', 'Link', 'Nav',
    'Ul', 'Ol', 'Li', 'Dl', 'Dt', 'Dd', 'Table', 'Thead', 'Tbody', 'Tfoot', 'Tr',
    'Th', 'Td', 'Caption', 'Col', 'Colgroup', 'Form', 'Input', 'Textarea',
    'Button', 'Select', 'Option', 'Label', 'Fieldset', 'Legend', 'Details',
    'Summary', 'Main', 'Header', 'Footer', 'Section', 'Article', 'Aside', 'Figure',
    'Figcaption', 'Mark', 'Small', 'Iframe', 'Object', 'Embed', 'Param', 'Video',
    'Audio', 'Source', 'Canvas', 'Svg', 'Math', 'Script', 'Noscript', 'Template', 'Slot']

for o in _all_: _g[o] = partial(ft, o.lower(), void_=o.lower() in voids)

# %% ../nbs/09_xml.ipynb #39834fcb
def Html(*c, doctype=True, **kwargs)->FT:
    "An HTML tag, optionally preceeded by `!DOCTYPE HTML`"
    res = ft('html', *c, **kwargs)
    if not doctype: return res
    return (ft('!DOCTYPE', html=True, void_=True), res)

# %% ../nbs/09_xml.ipynb #116c886e
class Safe(str):
    def __html__(self): return self

# %% ../nbs/09_xml.ipynb #254c8ff3
def _escape(s):
    return '' if s is None else s.__html__() if hasattr(s, '__html__') \
        else escape(s, quote=False) if isinstance(s, str) else s
def _noescape(s): return '' if s is None else s.__html__() if hasattr(s, '__html__') else s

# %% ../nbs/09_xml.ipynb #0255b96f
def _to_attr(k,v):
    if isinstance(v,bool):
        if v==True : return str(k)
        if v==False: return ''
    if isinstance(v,str) and ('&' in v or '<' in v or '>' in v): v = escape(v, quote=False)
    elif isinstance(v, Mapping): v = json.dumps(v)
    elif hasattr(v, '__html__'): v = v.__html__()
    else: v = str(v)
    qt = '"'
    if qt in v:
        qt = "'"
        if "'" in v: v = v.replace("'", "&#39;")
    return f'{k}={qt}{v}{qt}'

# %% ../nbs/09_xml.ipynb #ea224c94
_block_tags = {'div', 'p', 'ul', 'ol', 'li', 'table', 'thead', 'tbody', 'tfoot',
               'html', 'head', 'body', 'meta', 'title', '!doctype', 'input', 'script', 'link', 'style',
               'tr', 'th', 'td', 'section', 'article', 'nav', 'aside', 'header',
               'footer', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote'}
_inline_tags = {'a', 'span', 'b', 'i', 'u', 'em', 'strong', 'img', 'br', 'small',
                'big', 'sub', 'sup', 'label', 'input', 'select', 'option'}

_ws_significant = {'pre', 'code', 'textarea', 'script'}

# %% ../nbs/09_xml.ipynb #db55801a
def _to_xml(elm, lvl=0, indent=True, do_escape=True):
    "Convert `FT` element tree into an XML string"
    esc_fn = _escape if do_escape else _noescape
    if elm is None: return ''
    if hasattr(elm, '__ft__'): elm = elm.__ft__()
    if isinstance(elm, (tuple, L)): return ''.join(_to_xml(o, lvl=lvl, indent=indent, do_escape=do_escape) for o in elm)
    if isinstance(elm, bytes): return elm.decode('utf-8')
    if not isinstance(elm, FT): return f'{esc_fn(elm)}'

    tag,cs,attrs = elm.tag,elm.children,elm.attrs
    is_void = elm.void_
    is_block = tag in _block_tags
    if indent and (tag in _ws_significant or attrs.get('contenteditable') == 'true'): indent = False
    sp,nl = (' ' * lvl,'\n') if indent and is_block else ('','')
    nl_end = nl

    stag = tag
    if attrs:
        sattrs = ' '.join(_to_attr(k, v) for k, v in attrs.items() if v is not False and v is not None and (k=='_' or k[-1]!='_'))
        if sattrs: stag += f' {sattrs}'

    cltag = '' if is_void else f'</{tag}>'
    stag_ = f'<{stag}>' if stag else ''

    if not cs:
        if is_void: return f'{sp}{stag_}{nl_end}'
        else: return f'{sp}{stag_}{cltag}{nl_end}'
    if len(cs) == 1 and not isinstance(cs[0], (list, tuple, L, FT)) and not hasattr(cs[0], '__ft__'):
        content = esc_fn(cs[0])
        return f'{sp}{stag_}{content}{cltag}{nl_end}'

    res = f'{sp}{stag_}{nl}'
    for c in cs: res += _to_xml(c, lvl=lvl+2 if indent else 0, indent=indent, do_escape=do_escape)
    if not is_void: res += f'{sp}{cltag}{nl_end}'
    return Safe(res)

# %% ../nbs/09_xml.ipynb #e24ad4e0
def to_xml(*elms, lvl=0, indent=True, do_escape=True):
    "Convert `ft` element tree into an XML string"
    def _f(elm):
        if isinstance(elm, (list,tuple,L,FT)) or hasattr(elm, '__ft__'):
            return _to_xml(elm, lvl, indent, do_escape=do_escape)
        if isinstance(elm, bytes): return elm.decode('utf-8')
        return elm or ''
    return Safe('\n'.join(map(_f, elms)))

# %% ../nbs/09_xml.ipynb #dd054392
@patch
def __html__(self:FT): return to_xml(self, indent=False)
FT.__str__ = FT.__repr__ = FT.__html__

# %% ../nbs/09_xml.ipynb #43b0e38a
@patch
def _repr_html_(self:FT): return self.__html__()

# %% ../nbs/09_xml.ipynb #cd8a6aff
@patch
def __eq__(self:FT, other):
    if not isinstance(other, FT): return False
    return self.tag==other.tag and self.attrs==other.attrs and self.children==other.children

@patch
def __hash__(self:FT): return hash((self.tag, tuple(sorted(self.attrs.items())), self.children))

# %% ../nbs/09_xml.ipynb #30f4e3d8
def dict2xml(d, do_escape=False, unwrap=None):
    "Convert `d` to XML tags, one per key/value pair, unwrapping if only single key in `unwrap` exists"
    if unwrap and len(d)==1:
        if first(d) in listify(unwrap): return first(d.values())
    return to_xml(*[ft(k, str(v)) for k,v in d.items()], do_escape=do_escape)

# %% ../nbs/09_xml.ipynb #5f0e91e0
def highlight(s, lang='html'):
    "Markdown to syntax-highlight `s` in language `lang`"
    return f'```{lang}\n{to_xml(s)}\n```'

# %% ../nbs/09_xml.ipynb #39fab735
def showtags(s):
    return f"""<code><pre>
{escape(to_xml(s))}
</code></pre>"""

FT._repr_markdown_ = highlight

# %% ../nbs/09_xml.ipynb #b1a1fbd4
def _attr2tag(a): return re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '-', _fix_k(a)).lower()

def mk_getattr(f):
    "Create a module `__getattr__` for mapping undefined attributes to kebab-case HTML tags via factory `f`"
    def _getattr(tag):
        if tag.startswith('_') or tag[0].islower(): raise AttributeError(tag)
        return partialler(f, _attr2tag(tag))
    return _getattr

__getattr__ = mk_getattr(ft)

# %% ../nbs/09_xml.ipynb #d6b837e2
from collections.abc import Iterator
from keyword import iskeyword
from xml.sax.saxutils import escape as xml_escape, quoteattr


# %% ../nbs/09_xml.ipynb #8cb06993
_xml_uri = 'http://www.w3.org/XML/1998/namespace'
_xmlns_uri = 'http://www.w3.org/2000/xmlns/'
_xml_start = (r'A-Z_a-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02ff\u0370-\u037d\u037f-\u1fff'
              r'\u200c-\u200d\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd\U00010000-\U000effff')
_xml_local = re.compile(fr'[{_xml_start}][{_xml_start}\-.0-9\u00b7\u0300-\u036f\u203f-\u2040]*')
_xml_illegal = re.compile(r'[^\x09\x0a\x0d\x20-\ud7ff\ue000-\ufffd\U00010000-\U0010ffff]')

# %% ../nbs/09_xml.ipynb #b1031eff
def _xml_name(name):
    parts = name.split(':')
    if len(parts)>2 or any(not _xml_local.fullmatch(p) for p in parts): raise ValueError(f'Invalid XML name: {name!r}')
    if parts[0]=='xmlns': raise ValueError('Use ns for namespace declarations')
    return (parts[0], parts[1]) if len(parts)==2 else ('', name)

def _xml_value(value):
    value = ('true' if value else 'false') if isinstance(value, bool) else str(value)
    if _xml_illegal.search(value): raise ValueError('Illegal XML character')
    return value

def _xml_flatten(children):
    for child in children:
        if isinstance(child, (list, tuple, L, Iterator)): yield from _xml_flatten(child)
        elif child is not None: yield child

def _xml_qualify(name, prefix): return name if ':' in name or not prefix else f'{prefix}:{name}'

def _xml_keyword(name):
    prefix, sep, local = name.partition('__')
    if not sep: local = prefix
    if local.endswith('_') and iskeyword(local[:-1]): local = local[:-1]
    return f'{prefix}:{local}' if sep else local

# %% ../nbs/09_xml.ipynb #4abe3b40
class XML:
    "A detached XML expression with fixed namespace bindings."
    def __init__(self, tag, children, attrs, ns):
        self.tag,self.attrs,self.ns = tag,attrs,ns
        self.children = ()
        self(*children)

    def __call__(self, *children):
        "Append children and return this expression."
        self.children += tuple(self._child(c) for c in _xml_flatten(children))
        return self

    def _child(self, child):
        if isinstance(child, XML): return child
        if isinstance(child, str): return _xml_value(child)
        raise TypeError('XML children require expressions, strings, or ordered collections of them')


# %% ../nbs/09_xml.ipynb #642fc6f0
@patch
def _render(self:XML, inherited, output):
    output.append(f'<{self.tag}')
    for prefix, uri in self.ns.items():
        if inherited.get(prefix) != uri:
            name = f'xmlns:{prefix}' if prefix else 'xmlns'
            output.append(f' {name}={quoteattr(uri)}')
    for name, value in self.attrs: output.append(f' {name}={quoteattr(value)}')
    if not self.children:
        output.append('/>')
        return
    output.append('>')
    context = {**inherited, **self.ns}
    for child in self.children:
        if isinstance(child, XML): child._render(context, output)
        else: output.append(xml_escape(child, {'\r': '&#13;'}))
    output.append(f'</{self.tag}>')

@patch
def __str__(self:XML):
    output = []
    self._render({'xml': _xml_uri}, output)
    return ''.join(output)

@patch
def bytes(self:XML):
    "Serialize as UTF-8, without formatting whitespace."
    return str(self).encode('utf-8')

@patch
def _repr_markdown_(self:XML): return f'```xml\n{self}\n```'

# %% ../nbs/09_xml.ipynb #335a7366
class E:
    "Create a namespace-bound XML factory."
    _node_cls = XML

    def __init__(
        self, prefix='', # Default element prefix; empty uses the default namespace
        *, attr_ns=None, # Default attribute prefix; None leaves attributes unqualified
        ns=None, # Prefix-to-URI bindings, including prefixes used only in values
    ):
        self._prefix,self._attr_ns = prefix,attr_ns
        self._ns = {'': '', 'xml': _xml_uri, **(ns or {})}
        for p in (prefix, attr_ns):
            if p and (not _xml_local.fullmatch(p) or p=='xmlns'): raise ValueError(f'Invalid XML prefix: {p!r}')
        for p, uri in self._ns.items():
            if p and not _xml_local.fullmatch(p): raise ValueError(f'Invalid XML prefix: {p!r}')
            if not isinstance(p, str) or not isinstance(uri, str): raise TypeError('Namespace prefixes and URIs require strings')
            _xml_value(uri)
            if p=='xmlns' or uri==_xmlns_uri or (p=='xml')!=(uri==_xml_uri) or p and not uri:
                raise ValueError('Invalid reserved or empty namespace binding')

    def _namespace(self, prefix):
        if prefix not in self._ns: raise ValueError(f'Unknown XML prefix: {prefix!r}; supply ns')
        return self._ns[prefix]

    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        if name.endswith('_') and iskeyword(name[:-1]): name = name[:-1]
        return partial(self, name)

    def __call__(self, name, /, *children, attrs_=None, **attrs):
        tag = _xml_qualify(name, self._prefix)
        pairs = [(_xml_qualify(_xml_keyword(k), self._attr_ns), v) for k,v in attrs.items()]
        pairs += list((attrs_ or {}).items())
        ns,seen,values = dict(self._ns),set(),[]
        prefix, _ = _xml_name(tag)
        if prefix: ns[prefix] = self._namespace(prefix)
        for key, value in pairs:
            if value is None: continue
            prefix, local = _xml_name(key)
            if prefix: ns[prefix] = self._namespace(prefix)
            expanded = (ns[prefix] if prefix else '', local)
            if expanded in seen: raise ValueError(f'Duplicate XML attribute: {key!r}')
            seen.add(expanded)
            values.append((key, _xml_value(value)))
        return self._node_cls(tag, children, tuple(values), ns)

